local KI_RedClass = Color(220, 35, 35)
local KI_BlueClass = Color(35, 69, 220)
local KI_GreenClass = Color(103, 220, 35)
--local KI_YWLClass = Color(103, 220, 35) [probably for undead????]

--killicon.Add("weapon_vj_mh_rifle_assault", "vgui/manhunt/coltcom", KI_RedClass)
killicon.Add("weapon_vj_mh_shotgun", "vgui/manhunt/shotgun", KI_RedClass)
killicon.Add("weapon_vj_mh_shotgun_sawnoff", "vgui/manhunt/sawnoff", KI_RedClass)
--killicon.Add("weapon_vj_mh_pistol_smg", "vgui/manhunt/uzi", KI_BlueClass)
killicon.Add("weapon_vj_mh_melee_fireaxe", "vgui/manhunt/axe", KI_BlueClass)
killicon.Add("weapon_vj_mh_melee_bat_m", "vgui/manhunt/baseball", KI_RedClass)
killicon.Add("weapon_vj_mh_melee_bat_w", "vgui/manhunt/wbaseball", KI_RedClass)
--killicon.Add("weapon_vj_mh_melee_meat_cleaver", "vgui/manhunt/cleaver", KI_BlueClass)
--killicon.Add("weapon_vj_mh_pistol_heavy", "vgui/manhunt/desert", KI_BlueClass)
killicon.Add("weapon_vj_mh_pistol_light", "vgui/manhunt/glock", KI_BlueClass)
killicon.Add("weapon_vj_mh_pistol_light_ps2", "vgui/manhunt/glock", KI_BlueClass)
killicon.Add("weapon_vj_mh_melee_hammer", "vgui/manhunt/hammer", KI_BlueClass)
killicon.Add("weapon_vj_mh_melee_knife", "vgui/manhunt/knife", KI_BlueClass)
killicon.Add("weapon_vj_mh_melee_machete", "vgui/manhunt/machete", KI_BlueClass)
killicon.Add("weapon_vj_mh_pistol_nailgun", "vgui/manhunt/nailgun", KI_BlueClass)
killicon.Add("weapon_vj_mh_melee_nightstick", "vgui/manhunt/nightstick", KI_BlueClass)
killicon.Add("weapon_vj_mh_pistol_38r", "vgui/manhunt/revolver", KI_BlueClass)
--killicon.Add("weapon_vj_mh_melee_sickle", "vgui/manhunt/sickle", KI_BlueClass)
killicon.Add("weapon_vj_mh_melee_crowbar", "vgui/manhunt/crowbar", KI_BlueClass)
killicon.Add("weapon_vj_mh_melee_blackjack", "vgui/manhunt/smallbat", KI_BlueClass)
killicon.Add("weapon_vj_mh_rifle_sniper", "vgui/manhunt/sniper", KI_RedClass)
killicon.Add("weapon_vj_mh_melee_fists", "vgui/manhunt/fist", KI_GreenClass)